CREATE TABLE public.contacts (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	phone_number varchar(11) NOT NULL,
	email varchar(50) NOT NULL,
	ddd varchar(2) NOT NULL,
	CONSTRAINT "PK_contacts" PRIMARY KEY (id)
);