CREATE TABLE public.contacts (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NOT NULL,
	phone_number varchar(15) NOT NULL,
	email varchar(15) NOT NULL,
	CONSTRAINT "PK_contacts" PRIMARY KEY (id)
);

